# Generated by Django 2.1.1 on 2018-12-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=24)),
                ('request_time', models.CharField(max_length=24)),
                ('request_type', models.CharField(max_length=10)),
                ('request_url', models.CharField(max_length=64)),
                ('status_code', models.CharField(max_length=10)),
            ],
        ),
    ]
